// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp1kupImP5MsNH_LcxmOg2fRlSo22MH4o',
    appId: '1:831341864838:web:a2911ad595de1e00a9ee07',
    messagingSenderId: '831341864838',
    projectId: 'app-down-maternity',
    authDomain: 'app-down-maternity.firebaseapp.com',
    storageBucket: 'app-down-maternity.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEFYivQqdNN8LJ77I6dDCUFJpA627muaM',
    appId: '1:831341864838:android:cc0a02dcbba2f061a9ee07',
    messagingSenderId: '831341864838',
    projectId: 'app-down-maternity',
    storageBucket: 'app-down-maternity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0hLPBcCf4QJNANsKhxOJBbtokYKq0UfI',
    appId: '1:831341864838:ios:03e8e40452d28fd3a9ee07',
    messagingSenderId: '831341864838',
    projectId: 'app-down-maternity',
    storageBucket: 'app-down-maternity.appspot.com',
    iosClientId: '831341864838-lhqaqf9mvnrq8ja36qrbkhs06fllcg1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoSindromeDown',
  );
}
